server:
  type: default
  maxThreads: 100

  applicationConnectors:
    - type: http
      port: 25330

  adminConnectors:
    - type: http
      port: 25331

  requestLog:
    appenders:
      - type: console

logging:

  level: DEBUG

  appenders:
    - type: console
      threshold: INFO
      target: stderr
