server:
  type: default
  maxThreads: 100

  applicationConnectors:
    - type: http
      port: 25340

  adminConnectors:
    - type: http
      port: 25341

  requestLog:
    appenders:
      - type: console

logging:

  level: DEBUG

  appenders:
    - type: console
      threshold: INFO
      target: stderr
